platforms:
  enabled: true                         # 是否启用热榜平台抓取
  sources:
    - id: "toutiao"
      name: "今日头条"
    - id: "baidu"
      name: "百度热搜"
    - id: "wallstreetcn-hot"
      name: "华尔街见闻"
    - id: "thepaper"
      name: "澎湃新闻"
    - id: "bilibili-hot-search"
      name: "bilibili 热搜"
    - id: "cls-hot"
      name: "财联社热门"
    - id: "ifeng"
      name: "凤凰网"
    - id: "tieba"
      name: "贴吧"
    - id: "weibo"
      name: "微博"
    - id: "douyin"
      name: "抖音"
    - id: "zhihu"
      name: "知乎"

weight:
  rank_threshold: 10
  weight_config:
    RANK_WEIGHT: 0.6
    FREQUENCY_WEIGHT: 0.3
    HOTNESS_WEIGHT: 0.1

llm_executor:
  max_workers: 20